export const ORDER='ORDER';
export const FILTER='FILTER';
export const ERROR='ERROR';
export const ADD_ALL='ADD_ALL';
export const ADD_ALL_DIETS='ADD_ALL_DIETS';
export const SEARCH_RECIPES='SEARCH_RECIPES';

export const SET_PAGEITEMS_GLOBAL='SET_PAGEITEMS_GLOBAL';
export const SET_FIRSTINDEX_GLOBAL='SET_FIRSTINDEX_GLOBAL';
export const SET_CURRENTPAGE_GLOBAL='SET_CURRENTPAGE_GLOBAL';
export const SET_ITEMS_GLOBAL='SET_ITEMS_GLOBAL';

export const SET_RECIPESEARCH_GLOBAL='SET_RECIPESEARCH_GLOBAL';

export const RESET = 'RESET';

export const SET_UPD_ID='SET_UPD_ID';